## OpenMRS runtime configuration
connection.username=openmrs
connection.password=changeMeOpenMRS!
connection.url=jdbc:postgresql://openmrs-db:5432/openmrs
module.allow_web_admin=true
auto_update_database=true
encryption.vector=NzZhY2UyMjY0Mjk5NDIyNg==
encryption.key=tY4YVnowNvFrKVAoijkq6g==

